# You can use this file to setup the service locally, and start all the
# containers at once.
#
# Usage:
# - setup all the environment variables referenced below
# - install Docker Compose, see https://docs.docker.com/compose/install
# - open a console and `cd` into the folder that contains this file
# - run `docker-compose up`

version: "3"

services:
  telemetryagent:
    image: azureiotpcs/telemetry-agent-dotnet:0.x.y
    ports:
      - "9023:9023"
    environment:
      - PCS_TELEMETRYAGENT_DOCUMENTDB_CONNSTRING
      - PCS_TELEMETRY_WEBSERVICE_URL
      - PCS_CONFIG_WEBSERVICE_URL
      - PCS_IOTHUBMANAGER_WEBSERVICE_URL
      - PCS_IOTHUBREACT_AZUREBLOB_ACCOUNT
      - PCS_IOTHUBREACT_AZUREBLOB_KEY
      - PCS_IOTHUBREACT_AZUREBLOB_ENDPOINT_SUFFIX
      - PCS_IOTHUBREACT_HUB_NAME
      - PCS_IOTHUBREACT_HUB_ENDPOINT
      - PCS_IOTHUBREACT_ACCESS_CONNSTRING
